name: Check Pull Request

on:
  pull_request:
    branches:
      - master
jobs:
  release-test:
    name: release-test
    runs-on:
    - self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js with GitHub Package Registry
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        branch: main
        extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}